---
title: "fit"
author: "Nicholas Tierney"
date: "`r format(Sys.time(), '%x at %H:%M:%S %Z')`"
output: html_document
params:
  n_iterations_adapt: 100
  n_iterations_burnin: 100
  n_iterations_model: 100
  n_thin: 1
  n_chains: 1
  outcome: "dias"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      cache = TRUE)
analysis_path <- rprojroot::find_package_root_file()
knitr::opts_knit$set(analysis_path)
```

```{r load-libraries, include = FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(purrr)
library(rjags)
library(readr)
library(readxl)
library(lubridate)
library(feather)
library(data.table)
```

Get all of the inputs from the previous Rmd

```{r retrieve-data}
system.time({
# get RDS ---------------------------------------------------------------------
    # jags_model_data
    jags_dat_model <-
    readRDS(sprintf("%s/analysis/outputs/01_tidy_output/output_%s/jags_dat_model.rds",
                    analysis_path,
                    params$outcome))
})
```

```{r model-prep}
    # The names of the parameters
        model_params <- c("y_pred", # predictions from Y
                          "mu", # mu results
                          "beta_all", #
                          "beta_d", ## instead of beta[ID[i]], is is beta_d[ID[i]]
                          "beta_0", ## instead of alpha[ID[i]], it is beta_0[ID[i]]
                          "beta_dc", # the overall intercept for the number of days
                          "beta_0c", # the overall intercept for the... intercept.
                          "tau_0", # tau_0 instead of tau_alpha
                          "tau_d", # tau_d instead of tau_beta
                          "tau_y",
                          "sigma_0", # sigma_0 instead of sigma_alpha
                          "sigma_d", # sigma_d instead of sigma_beta
                          "sigma_y")

    # function to set the betas to be zero.
        jags_inits <- function(){
            list("beta_all" = c(rep(0, dim(jags_dat_model$X)[2])))
                }

```


```{r jags-model-string}

param_indic <- params$outcome

if (param_indic == "sys" | param_indic == "dias"){
    prior_sigmas <- 50
} else if (param_indic == "fev1_perc" | param_indic == "bmi"){
    prior_sigmas <- 100
}

model_string <- paste0("model {

       for(i in 1:n_obs){
       
       y[i] ~ dnorm(mu[i], tau_y)
       
       y_pred[i] ~ dnorm(mu[i], tau_y)
       
       for (r in 1:np){
       
       vec[i,r] <- beta_all[r]*X[i,r]
       
       }

       mu[i] <- sum(vec[i,1:np]) + beta_0[ID[i]] + beta_d[ID[i]] * x[i]

           ## instead of alpha[ID[i]], it is beta_0[ID[i]]
           ## instead of beta[ID[i]], is is beta_d[ID[i]]
       
       }
       
       for(j in 1:n_patients){
       
       # alpha[j] ~ dnorm(0, tau_0)
       # centering around beta_0c

       beta_0[j] ~ dnorm(beta_0c, tau_0)
       
       
       # beta[j] ~ dnorm(0, tau_d)
       # centering around beta_dc

       beta_d[j] ~ dnorm(beta_dc, tau_d)
       
       }
       
       # for(r in 1:3){
       for (r in 1:np){
       
       beta_all[r] ~ dnorm(0.0, 1.0e-3)
       
       }

       # for(r in 4:np){
       # #  test to shrink SEG to 0 so that I can search for problems
       # beta_all[r] ~ dnorm(0.0,1.0e12)
       # # 
       # }
        
       beta_0c ~ dnorm(0.0, 1.0e-3)
       beta_dc ~ dnorm(0.0, 1.0e-3)

       sigma_y ~ dunif(0, ", prior_sigmas, ") 
       sigma_d ~ dunif(0, ", prior_sigmas, ") 
       sigma_0 ~ dunif(0, ", prior_sigmas, ")

       tau_y <- 1 / pow(sigma_y, 2)
       tau_d <- 1 / pow(sigma_0, 2)
       tau_0 <- 1 / pow(sigma_d, 2)
       
       }")

```


```{r}
sprintf("running model with %s adaptive iterations", params$n_iterations_adapt)
```

```{r run-jags-adapt, cache.lazy = FALSE}

library(rjags)
system.time(
jags_model_adapt <- jags.model(textConnection(model_string),
                              data = jags_dat_model,
                              n.chains = params$n_chains,
                              inits = jags_inits,
                              n.adapt = params$n_iterations_adapt)
)

```

```{r}
sprintf("running model with %s burnin iterations", params$n_iterations_burnin)
```


```{r run-jags-burnin, cache.lazy = FALSE}

system.time(
jags_model_burnin <- coda.samples(model = jags_model_adapt,
                                       variable.names = model_params,
                                       n.iter = params$n_iterations_burnin)
)

```

```{r}
sprintf("running model with %s iterations", params$n_iterations_model)
```


```{r run-jags-fit, cache.lazy = FALSE}

system.time(
  jags_model_fit <- coda.samples(model = jags_model_adapt,
                                      variable.names = model_params,
                                      thin = params$n_thin,
                                      n.iter = params$n_iterations_model)
)

```


```{r create-directories}

# create the directories ----
# create the temporary directory
dir.create(sprintf("%s/analysis/outputs/02_fit_output", analysis_path), showWarnings = FALSE)

# create the directory for the outcome
dir.create(sprintf("%s/analysis/outputs/02_fit_output/output_%s",
                   analysis_path,
                   params$outcome),
           showWarnings = FALSE)


```

```{r save-02-fit-output}

system.time(
saveRDS(jags_model_fit,
        sprintf("%s/analysis/outputs/02_fit_output/output_%s/jags_model_fit.rds",
            analysis_path,
            params$outcome),
        compress = FALSE)
)
```

